server:
  applicationConnectors:
    - type: http
      port: 9085
  adminConnectors:
    - type: http
      port: 9086
logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: INFO
      target: stderr
    - type: file
      #threshold: ERROR
      # The file to which current statements will be logged.
      currentLogFilename: D://test/logs/example.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/example-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC
app:
  dbName: event_processor
  dbHost: 192.168.93.38
  dbUsername:
  dbPassword:
  inputProcessorUrl: http://192.168.93.61:9038
  handlerServiceUrl: ["http://192.168.93.61:9039/event-processor-handler", "http://192.168.93.61:9039/event-processor-handler"]
  cacheConfig:
  statsdHost:
  statsdAppPrefix: